apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-backend-deployment
  labels:
    app: mern-backend
  namespace: mern-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mern-backend
  template:
    metadata:
      labels:
        app: mern-backend

    spec:
      containers:
        - name: mern-backend
          image: rj1608/mern-backend:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: "PORT"
              value: "5000"