kind: Service
apiVersion: v1
metadata:
  name: mern-backend-service
  namespace: mern-app
spec:
  selector:
    app: mern-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
